### ISSUE TITLE
Main class diagram issues

### ISSUE THREAD

**Issue by VictorRutskin** [Guy-S-glitch/House-Finance-Manager#6]
1. main class field name as func name?? what does the addHouse field name means? its supposed to be a func?
if there is a purpose for this field then the name is confusing
2. what the heck is house1 field?

![image](https://github.com/Guy-S-glitch/House-Finance-Manager/assets/69360460/7e878909-e245-4c15-867a-7402fa8b0b13)

**Comment by Guy-S-glitch** [comment]
hi Lashaka.
firstly I'm very thankful for your honest review about my code.
I do believe that some of the fields/methods here are unnecessary and needs to be hidden and now they are
I also agree that the field's name House1 can be replace to the name house since there isn't any other houses, so as the field addHouse is field that right now isn't necessary  but it will be in future but for now it will be hidden.
hope you'll be satisfy with the current commit 👍.
